### ISSUE TITLE
`:content-type :json` breaks XHR reqeusts after cljs-http upgrade

### ISSUE THREAD

**Issue by royrutto** [onaio/milia#152]
After upgrade of `cljs-http` from `0.1.39` to `0.1.40`https://github.com/onaio/milia/commit/26624dfbf70c48cd56ab89aca3c66fb7a8c4c04e#diff-0fff143854a4f5c0469a3819b978a483R21, using `:content-type :json` in `http-options` e.g https://github.com/onaio/milia/blob/master/src/milia/api/rest_services.cljc#L30, cause a Status Code:415 Unsupported Media Type response (`{detail: "Unsupported media type "json" in request."}`).

Not sure why it happens after the upgrade. Removing `:content-type :json` from `http-options`on client-side requests prevents this. Rest Services endpoint is affected. Yet to know how many more endpoints are affected.

**Comment by pld** [comment]
Given this function and how it's referenced, we shouldn't need to set the
content type if we are passing JSON params
