### ISSUE TITLE
Core google Endpoint changed

### ISSUE THREAD

**Issue by KipSigei** [onaio/milia#177]
Google sheet has been extracted from core and has led to endpoint change. `/api/v1/export/google_auth` has changed to `/google/google_auth`

**Comment by pld** [comment]
This is a problem with the core code, that should be at `/api/v1/google/google_auth`

**Comment by Santei** [comment]
Oh okay. @denniswambua had communicated to us about the change not having `api/v1`

**Comment by Santei** [comment]
@pld ^

**Comment by pld** [comment]
That PR is a WIP that's failing tests and has a `QE-`, so it's clearly not done, you can assume the endpoint will be at `api/v1`, near where it is now
