### ISSUE TITLE
Configurable Variable for Thumbor Host

### ISSUE THREAD

**Issue by jasonrogena** [onaio/milia#248]
Make the thumbor host configurable so as to allow for us to point to a Thumbor host that isn't images.ona.io.

**Comment by morrismukiri** [comment]
@ivermac Here is an existing issue

**Comment by ivermac** [comment]
This issue was fixed by https://github.com/onaio/milia/pull/260. I'm going to create a new pull request that fixes a bug in the PR mentioned in the previous sentence which will close this issue
