### ISSUE TITLE
Tests on Milia break when running on lein 2.9.1 and jdk 11

### ISSUE THREAD

**Issue by RayceeM** [onaio/milia#272]
When running tests on lein 2.9.1 and jdk 11, some of the tests fail both locally and on Travis.
#### Tests failing

- Lein Eastwood
- Lein midje
- Lein cljsbuild once dev
- Lein cljsbuild once prod

A current hack that I have added on Travis is specifying the lein version and jdk version to use which are lein 2.8.1 and jdk 8
Can we get a better solution and approach to this?

**Comment by ivermac** [comment]
I think this is the preferred work-around until we properly test `lein 2.9.1` and `jdk 11`.

**Comment by FrankApiyo** [comment]
we now support lein `2.9.8` but we don't intend to support `jdk 11` just yet

**Comment by FrankApiyo** [comment]
actually, we now support `jdk 11` and `jdk 17`
