### ISSUE TITLE
Optional arguments using the :or construct aren't taken correctly in some cases

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/milia#300]
Seems that while using the `:or` construct in defn `:`'s are not expected 👉🏿  [more on this]( https://clojuredocs.org/clojure.core/defn)

These need to be fixed in the following places:

1. https://github.com/onaio/milia/blob/d9886f012347454f00719dbb31a0b6dc35ccd89c/src/milia/api/dataset.cljc
2. https://github.com/onaio/milia/blob/a6bd0d8a316e86f1d2c3ad732de8344b92091f0f/src/milia/api/io.cljs
3. https://github.com/onaio/milia/blob/4e910f05540da47de1731d787f91483f91870992/src/milia/api/merged_dataset.cljc

**Comment by pld** [comment]
oh wow, good job finding this error!
