### ISSUE TITLE
Add credetials atom use that instead of passing account around

### ISSUE THREAD

**Issue by pld** [onaio/milia#45]

**Comment by pld** [comment]
Note that this is a meaningful architectural change and needs good documentation in the code and in the README

**Comment by pld** [comment]
Ongoing work here, https://github.com/onaio/milia/compare/44-auth-atom?expand=1

**Comment by pld** [comment]
See the readme for the approach:

* all the `account` vars are being removed, the `io` namespaces will refer to `*credentials*`
* credentials are stored as a dynamic atom, we use earmuffs are call it *credentials* to show that it is dynamic, as is standard
 * we can use `binding` to rebind it for when we need to alter the state for a specific API call
* `parse-http` now takes, `method`, `url`, and a list options to be destructured as args

note that the tests are passing but only a small portion has been converted, the rest needs to be converted to remove `account`

I also have not touched `io.cljs` yet, it should be able to follow the same pattern as `io.clj`

**Comment by geoffreymuchai** [comment]
Thanks Peter for this update.

**Comment by geoffreymuchai** [comment]
@pld 
**Progress update**
I have updated all `clj` namespaces apart from the user.clj file.

**Comment by pld** [comment]
@geoffreymuchai made changes to the CLJS part of http.cljc, I think next up is handling the auth failure. Perhaps you can start this by adding tests for the request library based on how we want the auth failure to be handled, then modify it to get them passing.

I am concerned that more tests aren't failing when we make these changes.

**Comment by pld** [comment]
Splitting out the reload part, making this about putting the account atom into place

**Comment by pld** [comment]
see https://github.com/onaio/milia/issues/47
